version: '3.8'

services:
  web:
    build: 
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SECRET_KEY=${SECRET_KEY:-docker-secret-key-change-this}
      - FLASK_ENV=production
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local